# Generated by Django 3.2.18 on 2023-06-07 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('nombre_slug', models.SlugField(max_length=100, verbose_name='Nombre Slug')),
                ('ubicacion', models.CharField(max_length=50, verbose_name='Ubicacion')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('email', models.EmailField(max_length=150, null=True)),
                ('baja', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Varietal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('nombre_slug', models.SlugField(max_length=100, verbose_name='Nombre Slug')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Varietales',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('nombre_slug', models.SlugField(max_length=100, verbose_name='Nombre Slug')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Precio')),
                ('stock', models.CharField(max_length=10, verbose_name='Stock')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('cosecha', models.CharField(max_length=10, null=True, verbose_name='Cosecha')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
                ('activo', models.BooleanField(default=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.bodega')),
                ('varietal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.varietal')),
            ],
        ),
    ]
