# Generated by Django 3.2.18 on 2023-06-22 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('nombre_slug', models.SlugField(max_length=100, verbose_name='Nombre Slug')),
                ('ubicacion', models.CharField(max_length=50, verbose_name='Ubicacion')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('email', models.EmailField(max_length=150, null=True)),
                ('baja', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_slug', models.SlugField(max_length=100, verbose_name='Nombre Slug')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='MiembroAbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=150, null=True)),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
                ('domicilio', models.CharField(max_length=150, verbose_name='Domicilio')),
                ('nombre_usuario', models.CharField(max_length=150, verbose_name='Nombre de usuario')),
                ('cotraseña', models.CharField(max_length=150, verbose_name='Contraseña')),
                ('is_superuser', models.BooleanField(verbose_name='Superuser')),
                ('is_staff', models.BooleanField(verbose_name='Staff')),
                ('is_active', models.BooleanField(verbose_name='Activo')),
                ('legajo', models.CharField(max_length=10, verbose_name='Legajo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Varietal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('nombre_slug', models.SlugField(max_length=100, verbose_name='Nombre Slug')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Varietales',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_slug', models.SlugField(max_length=100, verbose_name='Nombre Slug')),
                ('num_comprobante', models.IntegerField(default=0, verbose_name='Numero comprobante')),
                ('fecha_venta', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('total_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total')),
                ('Detalle_venta', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administracion.detalle_venta')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('nombre_slug', models.SlugField(max_length=100, verbose_name='Nombre Slug')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Precio')),
                ('stock', models.CharField(max_length=10, verbose_name='Stock')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('cosecha', models.CharField(max_length=10, null=True, verbose_name='Cosecha')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
                ('activo', models.BooleanField(default=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.bodega')),
                ('varietal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.varietal')),
            ],
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='Producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.producto'),
        ),
        migrations.CreateModel(
            name='ClienteAbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=150, null=True)),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
                ('domicilio', models.CharField(max_length=150, verbose_name='Domicilio')),
                ('nombre_usuario', models.CharField(max_length=150, verbose_name='Nombre de usuario')),
                ('cotraseña', models.CharField(max_length=150, verbose_name='Contraseña')),
                ('is_superuser', models.BooleanField(verbose_name='Superuser')),
                ('is_staff', models.BooleanField(verbose_name='Staff')),
                ('is_active', models.BooleanField(verbose_name='Activo')),
                ('baja', models.BooleanField(default=0, null=True)),
                ('ventas', models.ManyToManyField(to='administracion.Venta')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
